### ISSUE TITLE
Никакого статического изменяемого состояния

### ISSUE THREAD

**Issue by AlphaBeth** [nymphaea-v1/Lab5#1]
https://github.com/nymphaea-v1/Lab5/blob/f1c6e395db7a0ef2859c41562f36f7b06180ce20/src/lab5/InputReader.java#L10-L12

Статические поля - только для констант.

**Comment by AlphaBeth** [comment]
Во всех остальных местах - тоже. Если есть изменяемое состояние, то оно должно быть в объекте.

**Comment by nymphaea-v1** [comment]
Все...........
https://github.com/nymphaea-v1/Lab5/commit/83ac42ece0398220d2501cf21ce3ac707128800e
