### ISSUE TITLE
Не надо так

### ISSUE THREAD

**Issue by AlphaBeth** [nymphaea-v1/Lab5#2]
https://github.com/nymphaea-v1/Lab5/blob/f1c6e395db7a0ef2859c41562f36f7b06180ce20/src/lab5/ticket/Ticket.java#L16-L24

Слишком сложный и не поддерживаемый код. В конструктор нужно передавать лист со строгим количеством аргументов, строго определенных типов. Одна опечатка - ошибка в рантайме, а не во время компиляции.

Нужно передавать каждое поле отдельным аргументом.

**Comment by nymphaea-v1** [comment]
"Перенесла" этот конструктор туда, где он должен был быть изначально - в TicketReader:
https://github.com/nymphaea-v1/Lab5/blob/b12f87bd1a4da9cc15977333fe90ad2604d75cc8/src/lab5/ticket/TicketReader.java#L85-L98
Теперь в Ticket два конструктора:
https://github.com/nymphaea-v1/Lab5/blob/b12f87bd1a4da9cc15977333fe90ad2604d75cc8/src/lab5/ticket/Ticket.java#L19-L29
https://github.com/nymphaea-v1/Lab5/blob/b12f87bd1a4da9cc15977333fe90ad2604d75cc8/src/lab5/ticket/Ticket.java#L31-L39

Этот конструктор по сути использовался только TicketReader в его же методах, где либо коллекция полей собиралась корректно и идеально под него, либо выбрасывался эксепшн, который далее обрабатывался.
