### ISSUE TITLE
Данная генерация айди не гарантирует уникальности.

### ISSUE THREAD

**Issue by AlphaBeth** [nymphaea-v1/Lab5#3]
https://github.com/nymphaea-v1/Lab5/blob/f1c6e395db7a0ef2859c41562f36f7b06180ce20/src/lab5/ticket/Ticket.java#L22

Могут возникнуть коллизии.

Нужно выработать стратегию, которая гарантированно будет генерировать уникальные айди (например, запоминать текущий самый большой идентификатор, а затем его инкрементировать).

**Comment by nymphaea-v1** [comment]
https://github.com/nymphaea-v1/Lab5/blob/b12f87bd1a4da9cc15977333fe90ad2604d75cc8/src/lab5/ticket/Ticket.java#L8
https://github.com/nymphaea-v1/Lab5/blob/b12f87bd1a4da9cc15977333fe90ad2604d75cc8/src/lab5/ticket/Ticket.java#L19-L29
https://github.com/nymphaea-v1/Lab5/blob/b12f87bd1a4da9cc15977333fe90ad2604d75cc8/src/lab5/ticket/Ticket.java#L31-L39

**Comment by AlphaBeth** [comment]
Напомните, что я говорил насчёт изменяемого статического состояния?
