### ISSUE TITLE
Реализовать более сложную логику сравнения

### ISSUE THREAD

**Issue by AlphaBeth** [nymphaea-v1/Lab5#4]
https://github.com/nymphaea-v1/Lab5/blob/f1c6e395db7a0ef2859c41562f36f7b06180ce20/src/lab5/ticket/Ticket.java#L123-L126

Использовать несколько полей, вводимых пользователем.

**Comment by nymphaea-v1** [comment]
👉👈
https://github.com/nymphaea-v1/Lab5/blob/b12f87bd1a4da9cc15977333fe90ad2604d75cc8/src/lab5/ticket/Ticket.java#L150-L157
https://github.com/nymphaea-v1/Lab5/blob/b12f87bd1a4da9cc15977333fe90ad2604d75cc8/src/lab5/ticket/Ticket.java#L159-L171

**Comment by AlphaBeth** [comment]
Почему equals только по id?

**Comment by AlphaBeth** [comment]
Почему есть equals, но нет hashCode?
