### ISSUE TITLE
Насколько я вижу, файлы скриптов не закрываются после чтения

### ISSUE THREAD

**Issue by AlphaBeth** [nymphaea-v1/Lab5#5]
Нужно грамотно управлять ресурсами, обязательно закрывать файлы

**Comment by nymphaea-v1** [comment]
InputReader.removeLastScanner теперь закрывает сканер, который удаляет из коллекции; сканер файла коллекции закрывается в конце CollectionManager.addFromFile; в InputReader.stopReading я не закрываю все сканеры потому что после вызова этого метода программа почти сразу же прекращает работу.
